"""updated db added assigned column

Revision ID: 10ae17c72007
Revises: 280a7727d8ce
Create Date: 2025-10-29 17:04:35.666787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ae17c72007'
down_revision: Union[str, Sequence[str], None] = '280a7727d8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('assigned', sa.Boolean(), nullable=True))
    op.add_column('test_assignments', sa.Column('q_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('test_assignments_t_id_fkey'), 'test_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'test_assignments', 'questions', ['q_id'], ['q_id'])
    op.drop_column('test_assignments', 't_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_assignments', sa.Column('t_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('test_assignments_t_id_fkey'), 'test_assignments', 'tests', ['t_id'], ['t_id'])
    op.drop_column('test_assignments', 'q_id')
    op.drop_column('questions', 'assigned')
    # ### end Alembic commands ###
