"""add test_url column,Description column

Revision ID: 1dd3c1f0997b
Revises: 3a54fa3f29ab
Create Date: 2025-10-17 11:40:51.975052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd3c1f0997b'
down_revision: Union[str, Sequence[str], None] = '3a54fa3f29ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('test_url', sa.String(length=2083), nullable=True))
    op.add_column('tests', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'description')
    op.drop_column('tests', 'test_url')
    # ### end Alembic commands ###
