"""Add new table

Revision ID: 3a54fa3f29ab
Revises: 
Create Date: 2025-10-15 12:41:51.557192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a54fa3f29ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('emp_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_emp_id'), 'employees', ['emp_id'], unique=False)
    op.create_table('tests',
    sa.Column('t_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('test_name', sa.String(length=150), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('no_of_mcq', sa.Integer(), nullable=True),
    sa.Column('no_of_short_ans', sa.Integer(), nullable=True),
    sa.Column('no_scenario_based', sa.Integer(), nullable=True),
    sa.Column('no_of_fill_blanks', sa.Integer(), nullable=True),
    sa.Column('no_of_true_false', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('duration > 0'),
    sa.CheckConstraint('max_marks > 0'),
    sa.CheckConstraint('total_questions = no_of_mcq + no_of_short_ans + no_scenario_based + no_of_fill_blanks + no_of_true_false'),
    sa.PrimaryKeyConstraint('t_id')
    )
    op.create_index(op.f('ix_tests_t_id'), 'tests', ['t_id'], unique=False)
    op.create_table('weightages',
    sa.Column('w_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('weightage', sa.DECIMAL(precision=4, scale=2), nullable=False),
    sa.CheckConstraint('weightage > 0'),
    sa.PrimaryKeyConstraint('w_id'),
    sa.UniqueConstraint('question_type')
    )
    op.create_index(op.f('ix_weightages_w_id'), 'weightages', ['w_id'], unique=False)
    op.create_table('questions',
    sa.Column('q_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('question_statement_options', sa.Text(), nullable=False),
    sa.Column('q_type', sa.String(length=50), nullable=False),
    sa.Column('correct_answers', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['t_id'], ['tests.t_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_index(op.f('ix_questions_q_id'), 'questions', ['q_id'], unique=False)
    op.create_table('results',
    sa.Column('r_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['tests.t_id'], ),
    sa.PrimaryKeyConstraint('r_id')
    )
    op.create_index(op.f('ix_results_r_id'), 'results', ['r_id'], unique=False)
    op.create_table('test_assignments',
    sa.Column('ta_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('completion_status', sa.Enum('Completed', 'Not Completed', name='completion_status'), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['tests.t_id'], ),
    sa.PrimaryKeyConstraint('ta_id')
    )
    op.create_index(op.f('ix_test_assignments_ta_id'), 'test_assignments', ['ta_id'], unique=False)
    op.create_table('employee_responses',
    sa.Column('e_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('t_id', sa.Integer(), nullable=False),
    sa.Column('q_id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('responses', sa.Text(), nullable=True),
    sa.Column('marks', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['q_id'], ['questions.q_id'], ),
    sa.ForeignKeyConstraint(['t_id'], ['tests.t_id'], ),
    sa.PrimaryKeyConstraint('e_id')
    )
    op.create_index(op.f('ix_employee_responses_e_id'), 'employee_responses', ['e_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_responses_e_id'), table_name='employee_responses')
    op.drop_table('employee_responses')
    op.drop_index(op.f('ix_test_assignments_ta_id'), table_name='test_assignments')
    op.drop_table('test_assignments')
    op.drop_index(op.f('ix_results_r_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_questions_q_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_weightages_w_id'), table_name='weightages')
    op.drop_table('weightages')
    op.drop_index(op.f('ix_tests_t_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_employees_emp_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
