"""message

Revision ID: 5c912300b1c0
Revises: fdb2d8c13f71
Create Date: 2025-10-30 10:24:12.535972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c912300b1c0'
down_revision: Union[str, Sequence[str], None] = 'fdb2d8c13f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('assigned', sa.Boolean(), nullable=True))
    op.add_column('test_assignments', sa.Column('q_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('test_assignments_t_id_fkey'), 'test_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'test_assignments', 'questions', ['q_id'], ['q_id'])
    op.drop_column('test_assignments', 't_id')
    op.drop_column('test_assignments', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_assignments', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('test_assignments', sa.Column('t_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'test_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('test_assignments_t_id_fkey'), 'test_assignments', 'tests', ['t_id'], ['t_id'])
    op.drop_column('test_assignments', 'q_id')
    op.drop_column('questions', 'assigned')
    # ### end Alembic commands ###
